### ISSUE TITLE
glTF2 format isn't registered properly

### ISSUE THREAD

**Issue by silversquirl** [MasterQ32/zig-assimp#7]
Enabling the `glTF2` format doesn't seem to work properly. `aiGetExtensionList` doesn't show `*.gltf` or `*.glb`, both of which should be present.

**Comment by sergeypdev** [comment]
Try again with the latest version and make sure to pass `-Dformats=glTF,glTF2` to zig build.

Or `-Dformats=all` after https://github.com/MasterQ32/zig-assimp/pull/9 is merged.

**Comment by silversquirl** [comment]
Works now, thanks!
